---
- name: Install ensure_mysql_certificate_setup.sh
  become: true
  ansible.builtin.copy:
    src: ensure_mysql_certificate_setup.sh
    dest: "/root/.bin/"
    mode: '0700'
    owner: root
- name: Create the compose project directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/mysql"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0744'
- name: Create the compose project
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "/home/{{ ansible_user_id }}/mysql/docker-compose.yaml"
    owner: "{{ ansible_user_id }}"
    mode: '0644'
# Output of the hook can be found as part of the logs at: /var/log/letsencrypt/letsencrypt.log
- name: Create certificates for MySQL (mysql.kleinendorst.info)
  become: true
  ansible.builtin.command:
    cmd: >-
      /snap/bin/certbot certonly
        --dns-cloudflare
        --dns-cloudflare-propagation-seconds 120
        --dns-cloudflare-credentials '/root/.secrets/certbot/cloudflare.ini'
        --agree-tos -m {{ administration_email }}
        --deploy-hook '/root/.bin/ensure_mysql_certificate_setup.sh'
        -d mysql.kleinendorst.info
    creates: "/etc/letsencrypt/live/mysql.kleinendorst.info"
- name: Create and start services
  become: true
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user_id }}/mysql/"
- name: Add entry in /etc/hosts
  become: true
  notify: Restart dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_facts['default_ipv4']['address'] }} mysql.kleinendorst.info"
