$ANSIBLE_VAULT;1.1;AES256
35336237356535366537343132666432363439323436323733613662333561663061316438646530
3263366262393766646563666666336364666131623534610a363939303334663936646436636663
66633639326561656231633464636163633166643161643436633133363933316566353965313432
3863383633316635310a363333386338613765333263633635373663306436363566303234666339
32616564613735373165643735353632393934376139613833346139303030353462383466356462
61386464373065633964633130303461303663633530643936313964643166313933393236623564
32343635313631643830323935666366616130623562353962613637636534656234313061306662
30303934356330653331633436616431623831343433633838333237376439626265303362336130
62313436373237343639323162373635313131653734303833636531616539613632663766666239
61656361636462666262653332353537333664336437343435346266323337343635366130653461
31663932313462333866343763343761653361653637356561383261333430623436393837326633
31643165313437383761316131333533646238356265373136313836313337356636303335636363
36653239626462376436333163303362616132363333646530383834636538383963616433343936
61396163623965396532386239326439316136303264663839373331383262346263646362623938
63323366363138643365626462336364396137646665636237306430356639333436363166636461
30333861656633393730
