$ANSIBLE_VAULT;1.1;AES256
34336338613062366131643735643335613466653733646461616464303634373763323833343334
3131376136333965333434326230643436393665343763370a376534626164306238333065383865
37343436343830653636636131306337333530393534636138646336323061653765316231386564
3233636261303334320a663063393734643461366632366531383936313034633733393166623261
30663832393139386361333033643730343832656163653439346661363838343962393937363631
39326332663138393938653038303362643764636338643931643539656334383231666466383936
64666631303038633639633934623963643737343031346665366465353835333264313135343036
34653737623862323336323232353434336233653961316166363036393534343433323039353535
63306362303937376362326434343063366239623136393761646466313731386130623565373031
63316563653438313836633662306138326636616537366130313036663535613662663731383039
37653132656435383036376535356463376464353264343930386634613436616634656164653534
36353361313762643339386639393336313032623233376433623534313738633231626266383336
39663339323636646337646135656134313462343533663666333234656433336464
