$ANSIBLE_VAULT;1.1;AES256
64626435313633386263306162623062346338353832323966323865656438313764313761656539
6339333136613932343437633564343966653261376361350a653930643161323933616430353536
61626437666263353532376362376561323963336636636334636162613834366236343666366662
3766613564636338620a393436373834386236303232643862323732346338613561313937313035
31656363356336373563643265656235636436353735623532626236663363333330333931303338
30343137303830656330653235373237653464333436643463396630333763643531356364303031
32633764363461363837353061376165373462366431353839313538323933346135626434353435
36303339613439653736346138386361353761616532363938656162316138313430656539383265
62306638663437316637333961356132383935323735663265613836633433663036656130313834
35663261633536376534346462353435643338383961336436666636633833623035626337653539
63376432353165333463346130626333373961323138316132633234643365633364663734653534
62633865653935346237303364366333386563383135373531376335376664343763323032653965
36303730363437306564396162663832373332643361326235636337623138616334326135306439
31616164613035333866633666656335323332616466326439656539376339363331313634383162
38646663383263376337356630666261383061316538623132393565626662643637636430326136
34376337633063303961
